### ISSUE TITLE
How to use the INS Data in local coordinate

### ISSUE THREAD

**Issue by kahowang** [minwoo0611/helipr_file_player#7]
Hi minwoo, @minwoo0611 
Thank you very much for your excellent work, I noticed that the **HeliPR-Dataset** provides **INS** Data from the **SPAN-CPT7** sensor, and I have a few questions I would like to consult you.

1. I would like to use the `INS Data` as the ground truth for the dataset, but the 'inertial_data/inspva.csv' file only provides` [timestamp, latitude, longitude, height, north velocity, east velocity, up velocity, roll, pitch, azimuth, status]`, and does not provide the information converted to the local coordinate system. How can I operate to convert the `[latitude, longitude, and height]` information from the `INS Data` into `XYZ` information in the local coordinate system, in order to use it for SLAM ground truth verification.

2. As you mentioned, `“the HeLiPR Dataset offers individual LiDAR ground truth data. These ground truths are indeed formulated based on the extrinsic calibration of each LiDAR sensor and the B-Spline Interpolation, which is tailored to the unique acquisition timestamp of each LiDAR”.`
May I ask if the individual LiDAR groundtruth is also converted based on INS Data? What exactly is the process?

Looking forward for your reply~
Best regards, 
kaho

**Comment by minwoo0611** [comment]
Hello, @kahowang 

Thank you very much for your kind words and for reaching out with your questions.

To convert the [latitude, longitude, and height] from the INS Data to XYZ coordinates in the local coordinate system for SLAM ground truth verification, you need to follow these steps:

1. **Convert Latitude and Longitude to UTM Coordinates**: The first step is to convert the latitude and longitude values to UTM (Universal Transverse Mercator) coordinates. This will give you a metric representation of the data.
  
2. **Formulate Ground Truth Using B-Spline Interpolation**: Since there may be temporal discrepancies between the data points, use B-Spline interpolation to align the INS data with the acquisition timestamps of each LiDAR sensor.

3. **Apply Extrinsic Calibration**: Perform an extrinsic transformation between sensors to address spatial discrepancies. This will align the INS data with the local coordinate system accurately.

As for the individual LiDAR ground truth data mentioned, yes, it is also converted based on INS Data. The process involves using the INS Data to provide accurate positional information and then aligning the LiDAR data with this information using the methods described above.

For more detailed steps and explanations, please refer to [our article](https://arxiv.org/pdf/2309.14590).

If you have any more questions or need further assistance, feel free to create an issue or reach out again.

Best regards,  
Minwoo

**Comment by kahowang** [comment]
Hello, @minwoo0611 

Thank you for your reply.
Regarding the section on **INS-IMU Extrinsic Calibration**, you mentioned using the **hand-eye calibration** method for calibration. Could you please inform me if there is any open-source code available for this part in HeliPR dataset, or if there are any references you could recommend?

Looking forward for your reply~
Best regards,
kaho

**Comment by minwoo0611** [comment]
Hello, @kahowang 

Sorry for the late reply.

As you mentioned, we utilize hand-eye calibration. Since hand-eye calibration requires solving AX=XB, we use this GitHub library: [SolveAXXB](https://github.com/zhixy/SolveAXXB).

I hope this message can help you.

Thank you.

Best regards,
Minwoo
